# Generated by Django 6.0.4 on 2026-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
